openshift/openshift-restclient-java

src/main/java/com/openshift/internal/restclient/DefaultClient.java, src/main/java/com/openshift/internal/restclient/KubernetesAPIVersion.java, src/main/java/com/openshift/internal/restclient/model/Status.java, src/main/java/com/openshift/internal/restclient/model/properties/ResourcePropertiesRegistry.java, src/main/java/com/openshift/internal/restclient/model/properties/ResourcePropertyKeys.java, src/main/java/com/openshift/restclient/http/IHttpClient.java, src/main/java/com/openshift/restclient/http/IHttpStatusCodes.java, src/main/java/com/openshift/restclient/model/IStatus.java, src/test/java/com/openshift/internal/restclient/model/V1Beta3StatusTest.java, src/test/java/com/openshift/restclient/utils/Samples.java, src/test/resources/samples/openshift3/v1beta3_status.json
@adietish found our issue when reconnecting after eclipse session restart.  Per my discussion with @maxandersen , im putting this into master
=> [OSJC-157] Throw unauthorized exception when a 403 status is returned

src/main/java/com/openshift/internal/restclient/model/BuildConfig.java, src/main/java/com/openshift/internal/restclient/model/build/STIBuildStrategy.java, src/main/java/com/openshift/internal/restclient/model/build/SourceBuildStrategy.java, src/main/java/com/openshift/internal/restclient/model/properties/OpenShiftApiModelProperties.java, src/main/java/com/openshift/restclient/model/build/BuildStrategyType.java, src/main/java/com/openshift/restclient/model/build/ISTIBuildStrategy.java, src/main/java/com/openshift/restclient/model/build/ISourceBuildStrategy.java, src/test/java/com/openshift/internal/restclient/model/v1beta3/BuildConfigTest.java, src/test/resources/samples/openshift3/v1beta3_build_config.json
@adietish specific fix for build strategy only
=> [OSJC-174] Add source build strategy

src/main/java/com/openshift/internal/restclient/DefaultClient.java
=> [OSJC-217] Use the resources version when creating lists of things

src/main/java/com/openshift/internal/restclient/capability/server/ServerTemplateProcessing.java
If this is not done and there is an error creating the resource on server, NPE is thrown.
=> Override getName method

pom.xml, src/main/java/com/openshift/internal/restclient/DefaultClient.java, src/main/java/com/openshift/internal/restclient/SSLCertificateCallbackAdapter.java, src/main/java/com/openshift/internal/restclient/URLBuilder.java, src/main/java/com/openshift/internal/restclient/WatchClient.java, src/main/java/com/openshift/internal/restclient/http/UrlConnectionHttpClient.java, src/main/java/com/openshift/internal/restclient/model/KubernetesResource.java, src/main/java/com/openshift/internal/restclient/model/Service.java, src/main/java/com/openshift/internal/restclient/model/properties/ResourcePropertyKeys.java, src/main/java/com/openshift/restclient/IClient.java, src/main/java/com/openshift/restclient/IOpenShiftWatchListener.java, src/main/java/com/openshift/restclient/http/IHttpClient.java, src/main/java/com/openshift/restclient/model/IResource.java, src/main/java/com/openshift/restclient/model/IService.java, src/test/java/com/openshift/internal/restclient/IntegrationTestHelper.java, src/test/java/com/openshift/internal/restclient/URLBuilderTest.java, src/test/java/com/openshift/internal/util/ClientWatchIntegrationTest.java
@fbricon @adietish Please review
=> [OSJC-225] Add watch support for resources

pom.xml
With the new jar.outputDir property, one can now automatically generate the rest client jar
directly in the Eclipse org.jboss.tools.openshift.client/lib folder
- Right-click on the openshift-rest-client-java project
- Run As > Maven Build
- set goals=package
- add jar.outpuDir property, set the absolute path to org.jboss.tools.openshift.client/lib as value
- In the refresh tab, enable refresh resources upon completion
- click specify resources..., select org.jboss.tools.openshift.client/lib
Run, profit!
=> Make default jar output location configurable

src/main/java/com/openshift/internal/restclient/model/BuildConfig.java, src/main/java/com/openshift/internal/restclient/model/ImageStream.java, src/main/java/com/openshift/internal/restclient/model/image/TagReference.java, src/main/java/com/openshift/restclient/model/Annotatable.java, src/main/java/com/openshift/restclient/model/IBuildConfig.java, src/main/java/com/openshift/restclient/model/IImageStream.java, src/main/java/com/openshift/restclient/model/IResource.java, src/main/java/com/openshift/restclient/model/image/ITagReference.java, src/test/java/com/openshift/internal/restclient/model/v1/ImageStreamTest.java, src/test/resources/samples/openshift3/v1_image_stream.json
=> [OSJC-232] Update ImageStream to support jbt explorer view

src/main/java/com/openshift/internal/restclient/http/UrlConnectionHttpClient.java
@jcantrill a (non-hack) version of the change to set content-type so we can start builds with the latest origin rebase
=> set content-type to application/json on POST/PUT

src/main/java/com/openshift/internal/restclient/DefaultClient.java, src/main/java/com/openshift/internal/restclient/ResourceFactory.java, src/main/java/com/openshift/restclient/ClientBuilder.java, src/main/java/com/openshift/restclient/ClientFactory.java, src/main/java/com/openshift/restclient/IResourceFactory.java, src/test/java/com/openshift/internal/restclient/DefaultClientTest.java
=> [OSJC-238] Make IResourceFactory pluggable

src/main/java/com/openshift/internal/restclient/capability/resources/DeployCapability.java, src/test/java/com/openshift/internal/restclient/capability/resources/DeployCapabilityTest.java
=> [JBIDE-21715] fix deploy when missing a resource controller

src/main/java/com/openshift/internal/restclient/model/EnvironmentVariable.java, src/main/java/com/openshift/internal/restclient/model/ModelNodeAdapter.java, src/main/java/com/openshift/internal/restclient/model/ReplicationController.java, src/main/java/com/openshift/restclient/model/IConfigMapKeySelector.java, src/main/java/com/openshift/restclient/model/IEnvironmentVariable.java, src/main/java/com/openshift/restclient/model/IObjectFieldSelector.java, src/main/java/com/openshift/restclient/model/IReplicationController.java, src/main/java/com/openshift/restclient/model/ISecretKeySelector.java, src/test/java/com/openshift/internal/restclient/model/v1/ReplicationControllerTest.java
=> [OSJC-240] Set deploymentconfig env vars

src/main/java/com/openshift/internal/restclient/DefaultClient.java, src/main/java/com/openshift/internal/restclient/ResourceFactory.java, src/main/java/com/openshift/internal/restclient/capability/CapabilityInitializer.java, src/main/java/com/openshift/internal/restclient/capability/resources/DeployCapability.java, src/main/java/com/openshift/internal/restclient/capability/resources/ImageStreamImportCapability.java, src/main/java/com/openshift/internal/restclient/model/ImageStream.java, src/main/java/com/openshift/internal/restclient/model/KubernetesResource.java, src/main/java/com/openshift/internal/restclient/model/image/ImageStreamImport.java, src/main/java/com/openshift/restclient/ResourceKind.java, src/main/java/com/openshift/restclient/capability/resources/IImageStreamImportCapability.java, src/main/java/com/openshift/restclient/model/IImageStream.java, src/main/java/com/openshift/restclient/model/image/IImageStreamImport.java, src/test/java/com/openshift/internal/restclient/capability/resources/ImageStreamImportCapabilityTest.java, src/test/java/com/openshift/internal/restclient/model/v1/ImageStreamImportTest.java, src/test/java/com/openshift/restclient/utils/Samples.java, src/test/resources/samples/openshift3/v1_image_stream.json, src/test/resources/samples/openshift3/v1_image_stream_import.json
This PR adds support for ImageStreamImport to fix the referenced issue.  It allows image metadata to be retrieved via openshift without having a connection to a docker daemon
cc @adietish @fbricon 
[test]
=> [JBIDE-21626] Add ImageStreamImport Capability

src/main/java/com/openshift/restclient/images/DockerImageURI.java
Prevent NPE when tag is null in constructor.
make the 'LATEST' field public to reuse it elsewhere.
=> Fixes in DockerImageURI

pom.xml, src/main/java/com/openshift/internal/restclient/capability/resources/DockerRegistryImageStreamImportCapability.java, src/main/java/com/openshift/internal/restclient/capability/resources/ImageStreamImportCapability.java, src/main/java/com/openshift/internal/restclient/model/ModelNodeBuilder.java, src/main/java/com/openshift/internal/restclient/model/image/ImageStreamImport.java, src/main/java/com/openshift/restclient/ClientBuilder.java, src/main/java/com/openshift/restclient/http/IHttpConstants.java, src/main/java/com/openshift/restclient/images/DockerImageURI.java, src/test/java/com/openshift/internal/restclient/IntegrationTestHelper.java, src/test/java/com/openshift/internal/restclient/capability/resources/ImageStreamImportCapabilityIntegrationTest.java
=> [OSJC-244] Retrieve metadata from dockerhub v2 registry

src/main/java/com/openshift/internal/restclient/capability/CapabilityInitializer.java, src/main/java/com/openshift/internal/restclient/capability/resources/PropertyAccessCapability.java, src/main/java/com/openshift/restclient/capability/resources/IPropertyAccessCapability.java, src/test/java/com/openshift/internal/restclient/capability/resources/PropertyAccessCapabilityTest.java
Limited access to underlying json that is impl independent by providing a map.  Also allow access to an individual map entry as a string requiring user to convert.  This is trying to provide some access without fully duplicating DMR
cc @adietish @fbricon
=> [OSJC-205] Access raw JSON as object map

src/main/java/com/openshift/internal/restclient/DefaultClient.java, src/main/java/com/openshift/internal/restclient/http/UrlConnectionHttpClient.java, src/main/java/com/openshift/internal/restclient/http/UrlConnectionHttpClientBuilder.java, src/main/java/com/openshift/restclient/ClientBuilder.java, src/test/java/com/openshift/internal/restclient/DefaultClientTest.java, src/test/java/com/openshift/internal/restclient/http/HttpClientTest.java
This stems from the dialogue with @jim-minter I pulled you into a week or so ago.
This change allows the trust manager in UrlConnectionHttpClient.java to properly validate a server certificate (vs. skipping TLS verification and calling out to the ISSLCertificateCallback).
As an FYI, currently in jenkins-plugin I have to maintain my own TrustStore and validate the cert when UrlConnectionHttpClient calls the ISSLCertificateCallback (btw, this also revealed that the JDK does *NOT* use a singleton pattern when it comes to the TrustStore related stuff ... something I was not expecting :-) ).
Once some form of this change is in the 4.0.0-SNAPSHOT, I'll remove that extra TrustStore in jenkins-plugin and just set the cert being used via ClientBuilder.
Other note:  the trust store …
=> allow import of cert to the trust for ssl validation

src/main/java/com/openshift/internal/restclient/capability/resources/OpenShiftBinaryRSync.java, src/main/java/com/openshift/restclient/capability/resources/IPortForwardable.java, src/main/java/com/openshift/restclient/capability/resources/IRSyncable.java, src/main/java/com/openshift/restclient/model/IResource.java, src/test/java/OpenshiftBinaryRSyncRetrievalIntegrationTest.java, src/test/java/com/openshift/internal/restclient/IntegrationTestHelper.java, src/test/java/com/openshift/internal/restclient/capability/resources/OpenshiftBinaryRSyncRetrievalIntegrationTest.java, src/test/resources/openshiftv3IntegrationTest.properties
The underlying 'rsync' process inputstream is returned to the caller
when the OpenShiftBinaryRSync#sync(Peer, Peer) method is invoked.
This inputstream can be then displayed in the IDE console.
Also added some javadocs and an integration test (requires some setup)
Signed-off-by: Xavier Coulon <xcoulon@redhat.com>
=> JBIDE-21326 - Server Adapter: Publishing is not telling me what it's doing

src/main/java/com/openshift/internal/restclient/capability/resources/AbstractOpenShiftBinaryCapability.java, src/main/java/com/openshift/internal/restclient/capability/resources/OpenShiftBinaryPodLogRetrieval.java, src/main/java/com/openshift/internal/restclient/capability/resources/OpenShiftBinaryPortForwarding.java, src/main/java/com/openshift/internal/restclient/capability/resources/OpenShiftBinaryRSync.java
Add the "--exclude='.git'" flag in the rsync command to exclude the '.git'
directory. Since there can be only one occurrence of this option,
excluding the '.git' directory seems like the best choice.
Also refactored the methods that generate the command line flags to simply return
a String that will be appended to the StringBuilder by the caller method.
Signed-off-by: Xavier Coulon <xcoulon@redhat.com>
=> JBIDE-21453 - Server Adapter: use rsync flag instead of local filtered-copy

src/main/java/com/openshift/internal/restclient/model/ImageStream.java, src/main/java/com/openshift/internal/restclient/model/KubernetesResource.java, src/main/java/com/openshift/internal/restclient/model/ObjectReference.java, src/main/java/com/openshift/internal/restclient/model/image/TagReference.java, src/main/java/com/openshift/internal/restclient/model/properties/ResourcePropertyKeys.java, src/main/java/com/openshift/restclient/model/IImageStream.java, src/test/java/com/openshift/internal/restclient/model/KubernetesResourceTest.java, src/test/java/com/openshift/internal/restclient/model/v1/ImageStreamTest.java
the jenkins plugin has a requirement to be able to `oc tag` across namespaces/projects; i'm currently handcrafting a ModelNode but got back around to updating the restclient API to do this; i'll leverage this form if you all are agreeable to merge
thanks
=> add cross project tagging

src/main/java/com/openshift/internal/restclient/capability/resources/AbstractOpenShiftBinaryCapability.java, src/main/java/com/openshift/internal/restclient/capability/resources/OpenShiftBinaryPodLogRetrieval.java, src/main/java/com/openshift/internal/restclient/capability/resources/OpenShiftBinaryPortForwarding.java, src/main/java/com/openshift/internal/restclient/capability/resources/OpenShiftBinaryRSync.java, src/main/java/com/openshift/restclient/capability/IBinaryCapability.java, src/main/java/com/openshift/restclient/capability/resources/IPodLogRetrieval.java, src/main/java/com/openshift/restclient/capability/resources/IPortForwardable.java, src/main/java/com/openshift/restclient/capability/resources/IRSyncable.java, src/test/java/OpenshiftBinaryRSyncRetrievalIntegrationTest.java, src/test/java/com/openshift/internal/restclient/capability/resources/OpenshiftBinaryPortForwardingIntegrationTest.java
The OpenShiftBinaryRSync#sync(Peer,Peer) returned an InputStream
that was the combination of the underlying Process#getInputStream()
with Process#getErrorStream(), which means that when an error occurred,
the process' error stream was already read and consumed, meaning that it
could not be read again when throwing an OpenShiftException.
Also, added an 'OpenShiftBinaryOption' enum to hold the optional arguments
to pass to the underlying 'oc' command, which means that it impacts all
3 classes implementing calls to 'oc' (rsync, port-forwarding and logs)
The side effect to this commit is that by default, no flags are passed.
=> JBIDE-21999 - Error during rsync

src/main/java/com/openshift/internal/util/JBossDmrExtentions.java, src/test/java/com/openshift/internal/util/JBossDmrExtentionsTest.java
[test] @fbricon @adietish 
during working on build from found an issue in our method to sanitize the json that was keeping us from getting port spec info from imagestream tags since all the relevant info is in the key.
=> fix sanitize to allow keys with empty content to handle port specs

pom.xml
This allows deploying to an alternate repository with 
mvn deploy -DaltSnapshotDeploymentRepository=jboss-snapshots-repository::default::https://origin-repository.jboss.org/nexus/content/repositories/snapshots
=> Update maven-deploy-plugin to 2.8.2

src/main/java/com/openshift/internal/restclient/model/Container.java, src/test/java/com/openshift/internal/restclient/model/v1/ReplicationControllerTest.java
fixes the case where the pull spec is being modified by the client code.
cc @fbricon 
[test]
=> [OSJC-252] Make Container#setImage respect the pull spec

src/main/java/com/openshift/internal/restclient/model/deploy/ImageChangeTrigger.java, src/main/java/com/openshift/restclient/model/deploy/IDeploymentImageChangeTrigger.java, src/test/java/com/openshift/internal/restclient/model/v1/DeploymentConfigTest.java, src/test/resources/samples/openshift3/v1_deployment_config.json
=> [OSJC-253] Allow setting of namespace on a dc image change trigger

pom.xml, src/main/java/com/openshift/internal/restclient/model/kubeclient/Cluster.java, src/main/java/com/openshift/internal/restclient/model/kubeclient/Context.java, src/main/java/com/openshift/internal/restclient/model/kubeclient/KubeClientConfig.java, src/main/java/com/openshift/internal/restclient/model/kubeclient/KubeClientConfigConstructor.java, src/main/java/com/openshift/internal/restclient/model/kubeclient/User.java, src/main/java/com/openshift/restclient/ClientBuilder.java, src/main/java/com/openshift/restclient/model/kubeclient/ICluster.java, src/main/java/com/openshift/restclient/model/kubeclient/IContext.java, src/main/java/com/openshift/restclient/model/kubeclient/IKubeClientConfig.java, src/main/java/com/openshift/restclient/model/kubeclient/IUser.java, src/main/java/com/openshift/restclient/model/kubeclient/KubeClientConfigSerializer.java, src/main/java/com/openshift/restclient/utils/BeanUtils.java, src/test/java/com/openshift/internal/restclient/model/kubeconfig/KubeClientConfigTest.java, src/test/java/com/openshift/restclient/utils/Samples.java, src/test/resources/samples/openshift3/v1_kubeconfig.yaml
The allows the reading of the kubeconfig file.  It does not provide any immediate support for the client to consume because we have not locked down the usecase ATM for consuming the kubeconfig file.
cc @adietish @fbricon 
Merging in for bases of any future work.
=> [OSJC-251] Allow library to read kubeconfig

src/main/java/com/openshift/internal/restclient/model/List.java, src/test/java/com/openshift/internal/restclient/model/v1/ListTest.java, src/test/java/com/openshift/restclient/utils/Samples.java, src/test/resources/samples/openshift3/v1_config_map_list_empty.json
Even though empty lists are required for some parts of the API, other parts allow lists to not be
defined. This patch changes the behavior when the list is not defined by returning an empty list
rather than failing.
It would be nice to still get failure when the list is required, but that would require some more rework of the client API. Let me know what you think.
=> Allow empty lists in responses

src/main/java/com/openshift/internal/restclient/model/ReplicationController.java, src/test/java/com/openshift/internal/restclient/model/v1/ReplicationControllerTest.java
This is only exposed through internal object. I realise there is some work in progress on volumes which will influence the public API when complete.
=> Allow secret volumes to be added to replication controllers. 

src/main/java/com/openshift/internal/restclient/model/ReplicationController.java, src/main/java/com/openshift/internal/restclient/model/volume/EmptyDirVolumeSource.java, src/main/java/com/openshift/internal/restclient/model/volume/PersistentVolumeClaimVolumeSource.java, src/main/java/com/openshift/internal/restclient/model/volume/SecretVolumeSource.java, src/main/java/com/openshift/internal/restclient/model/volume/VolumeSource.java, src/main/java/com/openshift/restclient/model/IReplicationController.java, src/main/java/com/openshift/restclient/model/volume/IEmptyDirVolumeSource.java, src/main/java/com/openshift/restclient/model/volume/IPersistentVolumeClaimVolumeSource.java, src/main/java/com/openshift/restclient/model/volume/ISecretVolumeSource.java, src/main/java/com/openshift/restclient/model/volume/IVolumeSource.java, src/main/java/com/openshift/restclient/model/volume/VolumeType.java, src/test/java/com/openshift/internal/restclient/model/v1/EmptyDirVolumeSourceTest.java, src/test/java/com/openshift/internal/restclient/model/v1/PVCVolumeSourceTest.java, src/test/java/com/openshift/internal/restclient/model/v1/ReplicationControllerTest.java, src/test/java/com/openshift/internal/restclient/model/v1/SecretVolumeSourceTest.java, src/test/java/com/openshift/restclient/utils/Samples.java, src/test/resources/samples/openshift3/v1_empty_dir_volume_source.json, src/test/resources/samples/openshift3/v1_pvc_volume_source.json, src/test/resources/samples/openshift3/v1_secret_volume_source.json
This pull request adds an interface to the replicationcontroller for adding volumes to a pod spec. I have only implemented support for EmptyDir, Secret and PersistentVolumeClaim, as that is what we need right now. Adding other implementations should be straightforward.
=> Add a volume source interface

src/main/java/com/openshift/internal/restclient/okhttp/WatchClient.java, src/main/java/com/openshift/restclient/ClientBuilder.java, src/test/java/com/openshift/internal/restclient/okhttp/WatchClientTest.java, src/test/java/com/openshift/restclient/WatchClientIntegrationTest.java
This PR fixes an issue from the okHttp client refactor that
* limited the number of running requests during watch
* clones the underlying client for each watch
cc @fbricon @adietish @scabanovich
=> fix watch client queue

src/main/java/com/openshift/internal/restclient/capability/resources/AbstractOpenShiftBinaryCapability.java
Replace env clear by remove('KUBECONFIG')
=> [OSJC-264] - Commit a821fd51cbec9fa9ea9f25a6f4b2603b3ba5271e breaks sync feature

README.md, src/main/java/com/openshift/internal/restclient/model/BuildConfig.java, src/main/java/com/openshift/internal/restclient/model/KubernetesResource.java, src/main/java/com/openshift/internal/restclient/model/build/BuildConfigBuilder.java, src/main/java/com/openshift/restclient/model/IBuildConfig.java, src/main/java/com/openshift/restclient/model/IObjectReference.java, src/main/java/com/openshift/restclient/model/build/IBuildConfigBuilder.java, src/test/java/com/openshift/internal/restclient/model/build/BuildConfigBuilderTest.java, src/test/java/com/openshift/internal/restclient/model/v1/ObjectRefTest.java
=> [OSJC-269] Fix setting spec.output for BuildConfig

src/main/java/com/openshift/internal/restclient/capability/resources/ProjectTemplateListCapability.java, src/main/java/com/openshift/restclient/capability/resources/IProjectTemplateList.java
- Extend IProjectTemplateList to allow custom common namespace
=> [JBIDE-23014] - Allow connections to configure the cluster namespace from which to get clusterwide templates

src/main/java/com/openshift/internal/restclient/capability/resources/BuildTrigger.java, src/main/java/com/openshift/internal/restclient/model/build/BuildRequest.java, src/main/java/com/openshift/restclient/capability/resources/IBuildTriggerable.java, src/main/java/com/openshift/restclient/model/build/IBuildRequest.java, src/test/java/com/openshift/internal/restclient/model/build/BuildRequestTest.java
In order to support feature request: https://trello.com/c/Yl4qomsw/878-5-additional-jenkins-plugin-enhancement-requests-from-github
Adding environment variable support to restclient on which Jenkins plugin relies.
fyi @gabemontero
=> Adding environment variable support to BuildRequest

src/main/java/com/openshift/internal/restclient/DefaultClient.java, src/main/java/com/openshift/internal/restclient/URLBuilder.java, src/main/java/com/openshift/restclient/IClient.java, src/test/java/com/openshift/internal/restclient/URLBuilderTest.java
Adding SubContext to execute jolokia request.
https://github.com/openshift/openshift-restclient-java/issues/214#issuecomment-249626878
Adding a map is not useful in my opinion, because it's just a subContext that is needed and not additional parameters.
=> addSubContext to UrlBuilder

src/main/java/com/openshift/internal/restclient/DefaultClient.java, src/main/java/com/openshift/internal/restclient/URLBuilder.java, src/main/java/com/openshift/internal/restclient/api/capabilities/PodExec.java, src/main/java/com/openshift/internal/restclient/capability/CapabilityInitializer.java, src/main/java/com/openshift/internal/restclient/okhttp/ResponseCodeInterceptor.java, src/main/java/com/openshift/restclient/api/capabilities/IPodExec.java, src/main/java/com/openshift/restclient/capability/IStoppable.java, src/test/java/com/openshift/internal/restclient/URLBuilderTest.java, src/test/java/com/openshift/internal/restclient/api/capabilities/PodExecIntegrationTest.java, src/test/java/com/openshift/internal/restclient/api/capabilities/PodExecTest.java
Feature to support exec function for OpenShift Jenkins plugin: https://trello.com/c/Yl4qomsw/878-5-additional-jenkins-plugin-enhancement-requests-from-github
fyi @gabemontero 
API use example:
```
final IPodExec.Options options = new IPodExec.Options();
options.stdErr(true);
options.stdOut(true);
options.container("ruby-hello-world");
IPod pod = client.get("pods", "ruby-hello-world-1-hy2xq", "myproject");
IStoppable v = pod.accept(new CapabilityVisitor<IPodExec, IStoppable>() {
@Override
public IStoppable visit(IPodExec capability) {
return capability.start( new IPodExec.IPodExecOutputListener() {
@Override
public void onOpen() {
System.out.println( "OPEN!" );
}
@Override
public void onStdOut(String message) {
System.out.println( "stdout: " + message );
}
@Override
public void …
```
=> Adding pod exec function

src/main/java/com/openshift/internal/restclient/capability/resources/PodLogRetrievalAsync.java, src/main/java/com/openshift/restclient/capability/resources/IPodLogRetrievalAsync.java, src/test/java/com/openshift/internal/restclient/capability/resources/PodLogRetrievalAsyncIntegrationTest.java
Exceptions when attempting to retrieve logs asynchronously from pods are currently swallowed in the okhttp dispatcher thread. Perhaps we could introduce a model similar to #220  ?
fyi @gabemontero
=> Expose errors during async log retrieval

src/main/java/com/openshift/internal/restclient/model/ReplicationController.java, src/main/java/com/openshift/restclient/model/IReplicationController.java, src/test/java/com/openshift/internal/restclient/model/v1/ReplicationControllerTest.java, src/test/resources/samples/openshift3/v1_replication_controller.json
add service account to replication controller
Ref: https://docs.openshift.com/enterprise/3.2/dev_guide/deployments.html#run-pod-with-different-service-account
=> add service account to replication controller

src/main/java/com/openshift/internal/restclient/ResourceFactory.java, src/main/java/com/openshift/internal/restclient/model/Container.java, src/main/java/com/openshift/internal/restclient/model/ReplicationController.java, src/main/java/com/openshift/internal/restclient/model/volume/HostPathVolumeSource.java, src/main/java/com/openshift/internal/restclient/model/volume/VolumeSource.java, src/main/java/com/openshift/restclient/IResourceFactory.java, src/main/java/com/openshift/restclient/model/IContainer.java, src/main/java/com/openshift/restclient/model/IReplicationController.java, src/main/java/com/openshift/restclient/model/volume/IHostPathVolumeSource.java, src/test/java/com/openshift/internal/restclient/DefaultClientIntegrationTest.java, src/test/java/com/openshift/internal/restclient/ResourceFactoryTest.java, src/test/java/com/openshift/internal/restclient/model/v1/HostPathVolumeSourceTest.java, src/test/java/com/openshift/internal/restclient/model/v1/ReplicationControllerTest.java
This PR provides convenience methods for adding volumes to the DC podspec
=> [OSJC-275] Add volumes to deploymentconfigs

src/main/java/com/openshift/internal/restclient/model/Pod.java, src/test/java/com/openshift/internal/restclient/model/v1/PodTest.java
Logic of Pod.getStatus() is fixed to copy that of
resources.js .filter('podStatus')
=> JBIDE-23463 Properties: Build pod has state of exit code 0 instead of correct status completed

src/main/java/com/openshift/internal/restclient/model/Service.java, src/main/java/com/openshift/restclient/model/IService.java, src/test/java/com/openshift/internal/restclient/model/v1/ServiceTest.java, src/test/resources/samples/openshift3/v1_service.json
Turns out that with https://github.com/openshift/origin/pull/10777 the field service.spec.portalID has been removed.  QE just uncovered it via https://github.com/openshift/jenkins-plugin/issues/122 (where an unlucky set of circumstances allowed it to slip through the jenkins-plugin's automated tests.
=> adjust to removal of service.spec.portalIP

src/main/java/com/openshift/restclient/ClientBuilder.java
for the jenkins plugin, we are better served to use the default hostname provider supplied by okhttp3 (i.e. `ISSLCertificateCallback.allowHostname`), but we still want supply logic in the `allowCertificate` path.
All this stems from the discussions with Clayton in https://github.com/openshift/origin/issues/12476
=> allow use of okhttp3 default hostname verifier with cert callback

src/main/java/com/openshift/internal/restclient/capability/resources/AbstractOpenShiftBinaryCapability.java
@adietish @jeffmaury @robstryker, i've checked it on Fedora 25 and Windows 10.
Please, check it on MacOS and once again on Linux and Windows.
=> jbide-23862: fix for spaces in path to oc binary

src/main/java/com/openshift/internal/restclient/DefaultClient.java, src/main/java/com/openshift/restclient/IClient.java, src/test/java/com/openshift/internal/restclient/DefaultClientTest.java, src/test/java/com/openshift/internal/restclient/TypeMapperFixture.java, src/test/java/com/openshift/restclient/utils/Samples.java, src/test/resources/samples/openshift3/api_kubernetes_version.json, src/test/resources/samples/openshift3/api_openshift_version.json
squashed version of https://github.com/openshift/openshift-restclient-java/pull/277. I've made it because of the wrong branch name and wrong jira numbers in the commit comments.
@jcantrill @adietish you can look here now
=> jbide 24539: User should be able to see what OpenShift version a connection is

pom.xml, src/main/java/com/openshift/internal/restclient/api/capabilities/PodExec.java
first step in fixing https://github.com/openshift/origin/issues/15330
this allowed my to exec into a pod via the openshift pipeline plugin for jenkins and the openshift-restclient-server against a 3.7 server.
it also works against 3.6 rc0
@jcantrill ptal
@deads2k fyi ... also, so you know, after this gets pushed to the maven repo, there will be subsequent steps to update the plugin and image before the extended test noted in https://github.com/openshift/origin/issues/15330 passes again and we can close it out
=> pod exec needs stdOut/stdErr set for 3.7 servers

pom.xml
Late bumping current master to 5.9.1-SNAPSHOT. This is a late bump
since a first change was already done without bumping.
The erroneous final artifact wasn't released to maven repository
though so this duplication is limited to git.
=> bump to 5.9.1-SNAPSHOT

pom.xml, src/test/java/com/openshift/internal/restclient/TypeMapperFixture.java, src/test/java/com/openshift/internal/restclient/okhttp/WatchClientTest.java
@jcantrill - still not sure how my prior openshift testing missed this, but I've now confirmed that bumping okhttp is a more invasive change.
Specifically, it appears that okhttp-ws has been deprecated (see [1], [2]) and replaced with native websocket support in okhttp3 around v3.5
The internal classes that okhttp-ws depend on no longer exist (I finally figured this out when sorting thorugh  [3]).
While similar, the replacement classes were different enough that switching to the new APIs was not a quick fix for me (and I won't have the cycles to complete it on the side).
Hence, seemed more prudent to revert https://github.com/openshift/openshift-restclient-java/commit/1b29d03c88c8b13133ad5814a11f84b87a46ef2e
restclient integration tests look OK.
apologies for the churn ... assuming nobody …
=> revert PR 284

src/main/java/com/openshift/internal/restclient/ApiTypeMapper.java
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
=> Fix wrong number of argument for String.format

pom.xml, src/main/java/com/openshift/internal/restclient/capability/resources/AbstractOpenShiftBinaryCapability.java, src/main/java/com/openshift/internal/restclient/capability/resources/OpenShiftBinaryPodLogRetrieval.java, src/main/java/com/openshift/internal/restclient/capability/resources/OpenShiftBinaryPortForwarding.java, src/main/java/com/openshift/internal/restclient/capability/resources/OpenShiftBinaryRSync.java, src/main/java/com/openshift/restclient/capability/IBinaryCapability.java, src/main/java/com/openshift/restclient/capability/resources/IPodLogRetrieval.java, src/main/java/com/openshift/restclient/capability/resources/IRSyncable.java, src/test/java/com/openshift/internal/restclient/capability/resources/OpenShiftBinaryPodLogRetrievalTest.java, src/test/java/com/openshift/internal/restclient/capability/resources/OpenShiftBinaryPortForwardingTest.java, src/test/java/com/openshift/internal/restclient/capability/resources/OpenShiftBinaryRSyncTest.java, src/test/java/com/openshift/internal/restclient/capability/resources/OpenshiftBinaryPodLogRetrievalIntegrationTest.java, src/test/java/com/openshift/internal/restclient/capability/resources/OpenshiftBinaryPortForwardingIntegrationTest.java, src/test/java/com/openshift/internal/restclient/capability/resources/OpenshiftBinaryRSyncRetrievalIntegrationTest.java, src/test/java/com/openshift/internal/restclient/capability/resources/testutils/BinaryCapabilityTestMocks.java
provides a fix for #318 
This is breaking the public API, thus it's suggested at 6.0.0-SNAPSHOT
=> [318] Multiple excludes for binary rsync

pom.xml, src/main/java/com/openshift/internal/restclient/DefaultClient.java, src/main/java/com/openshift/internal/restclient/URLBuilder.java
=> [JBIDE-26172] corrected request url when using api groups

src/main/java/com/openshift/internal/restclient/capability/resources/OpenShiftBinaryPortForwarding.java, src/test/java/com/openshift/internal/restclient/capability/resources/OpenShiftBinaryPortForwardingTest.java
=> [339] dont use -p when port forwarding (deprecated in oc 3.11)

src/main/java/com/openshift/internal/restclient/DefaultClient.java
/healthz/ready was deprecated in 3.10, gives 404. /healthz existed since
at least OS 1.5.
=> [#345] use /healthz for server health checks

src/main/java/com/openshift/restclient/utils/Base64Coder.java, src/test/java/com/openshift/internal/restclient/model/v1/SecretTest.java, src/test/resources/samples/openshift3/v1_secret.json
...to allow us to run on jdk9+
=> using java.util.Base64 instead of javax.xml.bind.DatatypeConverter

.travis.yml
=> Use JDK11 instead of JDK9 in travis

pom.xml
- Updated okhttp from 3.11.0 to 3.14.2
=> OSJC-285: fix CVE-2018-20200

.travis.yml
=> use "dist: trusty" in .travis.yml to fix oraclejdk8 build (#396)

pom.xml, src/main/java/com/openshift/internal/restclient/ApiTypeMapper.java, src/main/java/com/openshift/internal/restclient/DefaultClient.java, src/main/java/com/openshift/internal/restclient/capability/resources/DockerRegistryImageStreamImportCapability.java, src/main/java/com/openshift/internal/restclient/okhttp/OpenShiftAuthenticator.java, src/main/java/com/openshift/internal/restclient/okhttp/ResponseCodeInterceptor.java, src/main/java/com/openshift/restclient/ClientBuilder.java
=> close responses, avoid leaking connections (#394)

src/main/java/com/openshift/internal/restclient/okhttp/AuthenticatorInterceptor.java, src/main/java/com/openshift/internal/restclient/okhttp/OpenShiftRequestBuilder.java
The change here is all requests hold authentication means. If those are not present an unauthenticated request to the authentication endpoint is performed in order to retrieve the bearer token. Before this fix, the request to the authentication endpoint was holding an invalid bearer token (which was ignored in 3.x but causes a Resource Forbidden Exception in CRC/OS 4.2). This causes that authentication is performed.
The bug that's reporting this issue is filed in JBoss Tools: https://issues.jboss.org/browse/JBIDE-26899
=> authorize by direct request to auth-endpoint (was: using invalid bearer & authenticator indirection)

src/main/java/com/openshift/internal/restclient/okhttp/BasicChallengeHandler.java, src/main/java/com/openshift/restclient/http/IHttpConstants.java, src/test/java/com/openshift/internal/restclient/okhttp/BasicChallangeHandlerTest.java
=> correctly handle challenge headers with 'realm=' (#430)

src/main/java/com/openshift/restclient/capability/resources/IRSyncable.java
fixes #437 
With this PR logging is corrected to report paths instead of java object ids:
```
Could not sync all pods to folder /Users/adietish/Documents/jboss-workspaces/jbosstools-github/runtime-openshift/.metadata/.plugins/org.jboss.ide.eclipse.as.core/jbide-25303@jboss-fuse70-java-opensh/deploy/BOOT-INF
```
=> corrected IRSyncable#Peer#toString (#437)

src/main/java/com/openshift/internal/restclient/DefaultClient.java, src/test/java/com/openshift/internal/restclient/DefaultClientTest.java
This is the code change to fix issues [454](https://github.com/openshift/openshift-restclient-java/issues/454)
**What's changed**
- There will be a check if the payload used by `client.execute()` containing null values for `InputStream` parameter.
- Refactoring typo in the test
- Access modifier for `DefaultClient.getPayload()` changed to default to be accessible by the test
=> Ensure null payload (on DELETE method) is transformed into empty string

pom.xml
Signed-off-by: Ondrej Dockal <odockal@redhat.com>
=> Updage log4j libraries to 2.17.1 to fix CVE-2021-44832
