src/main/java/com/openshift/internal/restclient/model/BuildConfig.java
src/main/java/com/openshift/internal/restclient/model/KubernetesResource.java
src/main/java/com/openshift/internal/restclient/model/build/STIBuildStrategy.java
src/main/java/com/openshift/internal/restclient/model/properties/BuildConfigPropertyKeys.java
src/main/java/com/openshift/internal/restclient/model/properties/OpenShiftApiModelProperties.java
src/main/java/com/openshift/restclient/model/IBuildConfig.java
src/main/java/com/openshift/restclient/model/build/ISTIBuildStrategy.java
src/test/java/com/openshift/internal/restclient/model/v1beta3/BuildConfigTest.java

Not sure if this was the idea of the // FIXME, but it in general works.
Any bigger plans beyond this? If not I'll implement similar for BuildSource and BuildTriggers

Allow setting IBuildStrategy on BuildConfig

---

src/main/java/com/openshift/internal/restclient/capability/server/ServerTemplateProcessing.java
src/main/java/com/openshift/internal/restclient/model/properties/OpenShiftApiModelProperties.java
src/main/java/com/openshift/internal/restclient/model/properties/ResourcePropertyKeys.java
src/main/java/com/openshift/internal/restclient/model/template/Template.java
src/main/java/com/openshift/internal/util/JBossDmrExtentions.java
src/main/java/com/openshift/internal/util/UnregisteredPropertyException.java
src/main/java/com/openshift/restclient/model/template/ITemplate.java
src/test/java/com/openshift/internal/restclient/model/template/TemplateTest.java
src/test/java/com/openshift/internal/restclient/model/v1beta1/V1Beta1TemplateTest.java
src/test/java/com/openshift/internal/restclient/model/v1beta3/TemplateTest.java
src/test/resources/samples/openshift3/v1beta3_template.json

@adietish restclient fix to support adding labels to resources on new app creation

[OSJC-172] Add object label support to template

---

src/main/java/com/openshift/internal/restclient/DefaultClient.java
src/test/java/com/openshift/internal/restclient/DefaultClientIntegrationTest.java
src/test/java/com/openshift/internal/restclient/DefaultClientTest.java

[OSJC-192] Add legacy endpoint for v1beta3 and oapi endpoint for v1 plus

---

src/main/java/com/openshift/internal/restclient/capability/server/ServerTemplateProcessing.java
src/main/java/com/openshift/internal/restclient/model/template/Template.java
src/main/java/com/openshift/restclient/model/template/ITemplate.java

Moving from JBT to client lib as discussed here: https://github.com/jbosstools/jbosstools-openshift/pull/691/files#diff-b5469f1a64ca531f5d6a529b1236aaecR51

[OSJC-194] implemented Template#isMatching(String)

---

src/main/java/com/openshift/internal/restclient/DefaultClient.java
src/main/java/com/openshift/internal/restclient/http/HttpClientException.java
src/main/java/com/openshift/internal/restclient/http/UrlConnectionHttpClient.java

[JBIDE-20289] Unable to create a connection from resourceforbidden

---

src/main/java/com/openshift/internal/restclient/capability/resources/OpenShiftBinaryPortForwarding.java

[OSJC-198] Fix null port pairs when stopping port forwarding

---

src/main/java/com/openshift/internal/restclient/capability/CapabilityInitializer.java
src/main/java/com/openshift/internal/restclient/capability/resources/AbstractOpenShiftBinaryCapability.java
src/main/java/com/openshift/internal/restclient/capability/resources/OpenShiftBinaryPodLogRetrieval.java
src/main/java/com/openshift/internal/restclient/capability/resources/OpenShiftBinaryPortForwarding.java
src/main/java/com/openshift/restclient/capability/ICapability.java
src/main/java/com/openshift/restclient/capability/resources/IPodLogRetrieval.java
src/main/java/com/openshift/restclient/capability/resources/IPortForwardable.java
src/test/java/com/openshift/internal/restclient/capability/resources/OpenshiftBinaryPodLogRetrievalIntegrationTest.java

[OSJC-206] Expose pod logs using Openshift binary

---

src/main/java/com/openshift/internal/restclient/capability/resources/AbstractOpenShiftBinaryCapability.java
src/main/java/com/openshift/internal/restclient/capability/resources/OpenShiftBinaryPodLogRetrieval.java
src/main/java/com/openshift/internal/restclient/capability/resources/OpenShiftBinaryPortForwarding.java
src/main/java/com/openshift/restclient/capability/resources/IPodLogRetrieval.java

[OSJC-207] Supply auth token when getting pod logs

---

src/main/java/com/openshift/internal/restclient/model/template/Parameter.java
src/test/java/com/openshift/internal/restclient/model/template/ParameterTest.java

@jcantrill pls review, this is required for https://issues.jboss.org/browse/JBIDE-20452

[OSJC-209] impl'ed Paramater#equals and Parameter#hashCode

---

src/main/java/com/openshift/internal/restclient/DefaultClient.java
src/main/java/com/openshift/internal/restclient/model/BuildConfig.java
src/main/java/com/openshift/internal/restclient/model/build/WebhookTrigger.java
src/main/java/com/openshift/restclient/IClient.java
src/test/java/com/openshift/internal/restclient/model/build/WebhookTriggerTest.java
src/test/java/com/openshift/internal/restclient/model/v1/BuildConfigTest.java
src/test/java/com/openshift/internal/restclient/model/v1beta3/BuildConfigTest.java

[JBIDE-20467] Update triggers to use the format for the latest api

---

src/main/java/com/openshift/internal/restclient/URLBuilder.java
src/test/java/com/openshift/internal/restclient/URLBuilderTest.java

[OSJC-211] Remove trailing slashes from baseurl in UrlBuilder

---

src/main/java/com/openshift/internal/restclient/URLBuilder.java
src/test/java/com/openshift/internal/restclient/URLBuilderTest.java

[JBIDE-20504] Unable to delete projects

---

src/main/java/com/openshift/internal/restclient/model/build/WebhookTrigger.java
src/test/java/com/openshift/internal/restclient/model/build/WebhookTriggerTest.java

[JBIDE-20682] Fix webhook url secret case-sensitivity

---

src/main/java/com/openshift/internal/restclient/capability/resources/AbstractOpenShiftBinaryCapability.java
src/main/java/com/openshift/restclient/OpenShiftContext.java
src/test/java/com/openshift/restclient/OpenShiftContextTest.java

JBIDE-20763 : store 'oc' binary in ThreadLocal

---

src/main/java/com/openshift/internal/restclient/capability/CapabilityInitializer.java
src/main/java/com/openshift/internal/restclient/capability/resources/BuildCanceller.java
src/main/java/com/openshift/internal/restclient/capability/resources/BuildTrigger.java
src/main/java/com/openshift/internal/restclient/model/Build.java
src/main/java/com/openshift/internal/restclient/model/DeploymentConfig.java
src/main/java/com/openshift/internal/restclient/model/ImageStream.java
src/main/java/com/openshift/internal/restclient/model/ReplicationController.java
src/main/java/com/openshift/internal/restclient/model/build/BuildRequest.java
src/main/java/com/openshift/restclient/capability/resources/IBuildCancelable.java
src/main/java/com/openshift/restclient/capability/resources/IBuildTriggerable.java
src/main/java/com/openshift/restclient/model/IBuild.java
src/main/java/com/openshift/restclient/model/IDeploymentConfig.java
src/main/java/com/openshift/restclient/model/IImageStream.java
src/main/java/com/openshift/restclient/model/IReplicationController.java
src/main/java/com/openshift/restclient/model/build/IBuildRequest.java
src/test/java/com/openshift/internal/restclient/model/v1/DeploymentConfigTest.java

@jcantrill @adietish  @fbricon :  per discussion with @jcantrill , I'm alerting each of you to this PR, which is intended to extend the some of the REST resources to expose information needed by the V3 Jenkins plug-in work I'm doing.
Of course let me know whatever changes/additions you all want done prior to @jcantrill merging and deploying to the maven repo.
thanks

additions for v3 jenkins plugin

---

src/main/java/com/openshift/internal/restclient/model/Container.java
src/main/java/com/openshift/internal/restclient/model/DeploymentConfig.java
src/main/java/com/openshift/internal/restclient/model/Port.java
src/main/java/com/openshift/internal/restclient/model/ReplicationController.java
src/main/java/com/openshift/internal/restclient/model/volume/AbstractVolume.java
src/main/java/com/openshift/internal/restclient/model/volume/EmptyDirVolume.java
src/main/java/com/openshift/restclient/model/IContainer.java
src/main/java/com/openshift/restclient/model/IDeploymentConfig.java
src/main/java/com/openshift/restclient/model/IReplicationController.java
src/main/java/com/openshift/restclient/model/volume/IVolume.java
src/test/java/com/openshift/internal/restclient/model/v1/ReplicationControllerTest.java

This PR:
* Adds getters and setters to replication controller
* deploymentconfig extends replication controller
* adds IContainer type

[OSJC-222] Flush out replication controller attributes and methods

---

src/main/java/com/openshift/internal/restclient/model/template/Parameter.java
src/main/java/com/openshift/restclient/model/template/IParameter.java

make IParameters clonable

---

src/main/java/com/openshift/internal/restclient/DefaultClient.java
src/main/java/com/openshift/internal/restclient/WatchClient.java
src/main/java/com/openshift/internal/restclient/model/List.java
src/main/java/com/openshift/restclient/IClient.java
src/main/java/com/openshift/restclient/IOpenShiftWatchListener.java
src/test/java/com/openshift/restclient/ClientWatchIntegrationTest.java

This PR:
* Allows you to create a single watch in a namespace on multiple kinds

Watch multiple kinds at once

---

src/main/java/com/openshift/internal/restclient/DefaultClient.java
src/main/java/com/openshift/restclient/IClient.java
src/test/java/com/openshift/restclient/ClientWatchIntegrationTest.java

Refactor watch signiture

---

src/main/java/com/openshift/internal/restclient/DefaultClient.java
src/test/java/com/openshift/internal/restclient/DefaultClientTest.java

[OSJC-228] check for token equality in DefaultClient#equals

---

src/main/java/com/openshift/internal/restclient/WatchClient.java

This provides one websocket client per jvm per:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=444748

One Websocket client per JVM

---

pom.xml
src/main/java/com/openshift/internal/restclient/model/Container.java
src/main/java/com/openshift/internal/restclient/model/ModelNodeBuilder.java
src/main/java/com/openshift/internal/restclient/model/ReplicationController.java
src/main/java/com/openshift/internal/restclient/model/volume/VolumeMount.java
src/main/java/com/openshift/internal/restclient/model/volume/VolumeSource.java
src/main/java/com/openshift/restclient/model/IContainer.java
src/main/java/com/openshift/restclient/model/IReplicationController.java
src/main/java/com/openshift/restclient/model/volume/IVolumeMount.java
src/main/java/com/openshift/restclient/model/volume/IVolumeSource.java
src/test/java/com/openshift/internal/restclient/model/v1/ReplicationControllerTest.java

This PR:
* Add an emptydir mount source if the container has volumemounts
/cc @adietish @fbricon

[ OSJC-230] Add volume sources to dc when containers have volume mounts

---

pom.xml
src/main/java/com/openshift/internal/restclient/model/KubernetesResource.java
src/main/java/com/openshift/internal/restclient/model/ModelNodeAdapter.java
src/main/java/com/openshift/internal/restclient/model/ObjectReference.java
src/main/java/com/openshift/internal/util/JBossDmrExtentions.java
src/test/java/com/openshift/internal/util/JBossDmrExtentionsTest.java

Sanitize JSON output to remove nulls

---

src/main/java/com/openshift/internal/restclient/WatchClient.java
src/main/java/com/openshift/internal/restclient/capability/CapabilityInitializer.java
src/main/java/com/openshift/internal/restclient/capability/resources/UpdateableCapability.java
src/main/java/com/openshift/internal/restclient/model/Build.java
src/main/java/com/openshift/internal/restclient/model/DeploymentConfig.java
src/main/java/com/openshift/internal/restclient/model/KubernetesResource.java
src/main/java/com/openshift/internal/restclient/model/List.java
src/main/java/com/openshift/internal/restclient/model/build/BuildStatus.java
src/main/java/com/openshift/internal/restclient/model/deploy/ConfigChangeTrigger.java
src/main/java/com/openshift/internal/restclient/model/deploy/ImageChangeTrigger.java
src/main/java/com/openshift/internal/restclient/model/properties/ResourcePropertyKeys.java
src/main/java/com/openshift/restclient/capability/resources/IUpdatable.java
src/main/java/com/openshift/restclient/model/IBuild.java
src/main/java/com/openshift/restclient/model/IDeploymentConfig.java
src/main/java/com/openshift/restclient/model/IResource.java
src/main/java/com/openshift/restclient/model/build/IBuildStatus.java
src/main/java/com/openshift/restclient/model/deploy/IDeploymentImageChangeTrigger.java
src/test/java/com/openshift/internal/restclient/capability/resources/UpdateableCapabilityTest.java
src/test/java/com/openshift/internal/restclient/model/v1/BuildTest.java
src/test/java/com/openshift/internal/restclient/model/v1/DeploymentConfigTest.java
src/test/java/com/openshift/internal/restclient/model/v1/ListTest.java
src/test/java/com/openshift/restclient/utils/Samples.java
src/test/resources/samples/openshift3/v1_build.json
src/test/resources/samples/openshift3/v1_build_config_list.json
src/test/resources/samples/openshift3/v1_deployment_config.json

[OSJC-231] Update Build and ReplicationController to support changes in JBT explorer for deployments

[OSJC-231] Update Build and ReplicationController to

---

pom.xml

Generate sources to 'jar.outputDir'

---

pom.xml

Bump to 4.0.0 for api change

---

src/main/java/com/openshift/internal/restclient/model/Route.java
src/main/java/com/openshift/restclient/model/route/IRoute.java
src/test/java/com/openshift/internal/restclient/model/v1/RouteTest.java

fixes #105 by adding a factory method.
cc @adietish @fbricon 
[test]

#105 Allow Route TLS config to be edited

---

src/main/java/com/openshift/internal/restclient/URLBuilder.java
src/main/java/com/openshift/restclient/ResourceKind.java
src/test/java/com/openshift/restclient/ResourceKindTest.java

[OSJC-218] Refactor URLBuilder to remove typemap for kind pluralization

---

src/main/java/com/openshift/internal/restclient/capability/CapabilityInitializer.java
src/main/java/com/openshift/internal/restclient/capability/resources/DeployCapability.java
src/main/java/com/openshift/internal/restclient/model/DeploymentConfig.java
src/main/java/com/openshift/restclient/capability/resources/IDeployCapability.java
src/main/java/com/openshift/restclient/model/IReplicationController.java
src/test/java/com/openshift/internal/restclient/capability/resources/DeployCapabilityTest.java
src/test/java/com/openshift/internal/restclient/model/DeploymentConfigTest.java
src/test/java/com/openshift/internal/restclient/model/v1/ReplicationControllerTest.java
src/test/java/com/openshift/restclient/utils/ResourceTestHelper.java

cc @fbricon capability for deploy support in the client.  tools changes will utilize this.
[test]

[JBIDE-21624] Add deploy capability to IDeploymentConfig

---

src/main/java/com/openshift/internal/restclient/model/ReplicationController.java
src/test/java/com/openshift/internal/restclient/model/v1/ReplicationControllerTest.java

[OSJC-240] ensure existing variables are updated

---

src/main/java/com/openshift/internal/restclient/model/Build.java
src/main/java/com/openshift/internal/restclient/model/BuildConfig.java
src/main/java/com/openshift/internal/restclient/model/ModelNodeAdapter.java
src/main/java/com/openshift/internal/restclient/model/build/SourceBuildStrategy.java
src/main/java/com/openshift/internal/util/JBossDmrExtentions.java
src/main/java/com/openshift/restclient/model/build/ISourceBuildStrategy.java
src/test/java/com/openshift/internal/restclient/model/v1/BuildConfigTest.java

fixes #130. Allow user to set sourcebuildstrategy env vars

---

src/main/java/com/openshift/internal/restclient/capability/resources/OpenShiftBinaryPodLogRetrieval.java

JBIDE-22073 : pass pod log options to oc binary

---

src/main/java/com/openshift/internal/restclient/model/ReplicationController.java
src/test/java/com/openshift/internal/restclient/model/v1/ReplicationControllerTest.java

also test that setting replicas doesn't suffer from the same problem.

[JBIDE-22136] fix updating env vars when matching node is missing

---

src/main/java/com/openshift/internal/restclient/ResourceFactory.java
src/test/java/com/openshift/internal/restclient/ResourceFactoryTest.java

fix ResourceFactory#stub where it was not setting namespace

---

src/main/java/com/openshift/internal/restclient/model/JSONSerializeable.java
src/main/java/com/openshift/internal/restclient/model/ModelNodeAdapter.java
src/main/java/com/openshift/internal/restclient/model/build/SourceBuildStrategy.java
src/main/java/com/openshift/restclient/model/IEnvironmentVariable.java

fixes copying the env vars where tostring was assumed to be json

Fix bc config for env

---

src/main/java/com/openshift/internal/restclient/capability/CapabilityInitializer.java
src/main/java/com/openshift/internal/restclient/model/BuildConfig.java
src/main/java/com/openshift/internal/restclient/model/KubernetesResource.java
src/main/java/com/openshift/internal/restclient/model/build/BuildConfigBuilder.java
src/main/java/com/openshift/internal/restclient/model/build/GitBuildSource.java
src/main/java/com/openshift/internal/restclient/model/build/ImageChangeTrigger.java
src/main/java/com/openshift/internal/restclient/model/build/SourceBuildStrategy.java
src/main/java/com/openshift/restclient/model/IBuildConfig.java
src/main/java/com/openshift/restclient/model/IResourceBuilder.java
src/main/java/com/openshift/restclient/model/build/BuildTriggerType.java
src/main/java/com/openshift/restclient/model/build/IBuildConfigBuilder.java
src/main/java/com/openshift/restclient/model/build/ISourceBuildStrategy.java
src/test/java/com/openshift/internal/restclient/model/build/BuildConfigBuilderTest.java

@fbricon @adietish 
This PR allows for a fluent style building of a buildconfig used in the create from source workflow in JBT.  Please review

allow BuildConfig creation via fluent style builder

---

src/main/java/com/openshift/internal/restclient/model/image/ImageStreamImport.java
src/main/java/com/openshift/restclient/model/image/IImageStreamImport.java
src/test/java/com/openshift/internal/restclient/model/v1/ImageStreamImportTest.java

[OSJC-254] Fix null pointer when imagestreamimport

---

src/main/java/com/openshift/internal/restclient/DefaultClient.java
src/main/java/com/openshift/internal/restclient/ResourceFactory.java
src/main/java/com/openshift/internal/restclient/model/ConfigMap.java
src/main/java/com/openshift/restclient/ResourceKind.java
src/main/java/com/openshift/restclient/model/IConfigMap.java
src/test/java/com/openshift/internal/restclient/model/v1/ConfigMapTest.java
src/test/java/com/openshift/restclient/utils/Samples.java
src/test/resources/samples/openshift3/v1_config_map.json

@jcantrill I will probably work to add write functionality as well if I need it.

Add read support for ConfigMap resource

---

src/main/java/com/openshift/internal/restclient/model/ImageStream.java
src/test/java/com/openshift/internal/restclient/model/v1/ImageStreamTest.java

[OSJC-258] fix retrieving the dockerimageuri if its only found on status

---

src/main/java/com/openshift/internal/restclient/authorization/AuthorizationClient.java

This should fix the login timeout issue

Bugfix login timeout

---

src/main/java/com/openshift/internal/restclient/ApiTypeMapper.java
src/main/java/com/openshift/internal/restclient/URLBuilder.java
src/main/java/com/openshift/internal/restclient/capability/resources/ImageStreamImportCapability.java
src/main/java/com/openshift/restclient/UnsupportedEndpointException.java
src/test/java/com/openshift/internal/restclient/ApiTypeMapperTest.java
src/test/java/com/openshift/internal/restclient/TypeMapperFixture.java

Add UnsupportedResourceException for cases where we are trying to utilize newer functionality against an older server (e.g. ImageStreamImport)
cc @fbricon @adietish 
[test]

Add unsupported resource exception

---

src/main/java/com/openshift/internal/restclient/ApiTypeMapper.java
src/test/java/com/openshift/internal/restclient/ApiTypeMapperTest.java
src/test/java/com/openshift/internal/restclient/TypeMapperFixture.java

fix issue where an error is thrown during initialization which caused subsequent checks to not recognize valid types.
cc @fbricon @adietish 
[test]

fix case where error is thrown while trying to initialize ApiTypeMapper

---

src/main/java/com/openshift/internal/restclient/ApiTypeMapper.java

@adietish @fbricon  I think this is better then the sync block that was in the init routine.

remove synchronization block in preference for atomic

---

src/main/java/com/openshift/internal/restclient/okhttp/BasicChallangeHandler.java
src/test/java/com/openshift/internal/restclient/okhttp/BasicChallangeHandlerTest.java

fix nullpointer in BasicChallangeHandler when the username is null

---

src/main/java/com/openshift/internal/restclient/capability/resources/AbstractOpenShiftBinaryCapability.java

[JBIDE-22644] Unable to perform oc binary actions because of insecure flag

---

src/main/java/com/openshift/internal/restclient/DefaultClient.java
src/test/java/com/openshift/internal/restclient/DefaultClientIntegrationTest.java
src/test/java/com/openshift/internal/restclient/IntegrationTestHelper.java

[OSJC-263] fix unable to delete OpenShift resources

---

src/main/java/com/openshift/internal/restclient/ApiTypeMapper.java
src/main/java/com/openshift/internal/restclient/DefaultClient.java
src/main/java/com/openshift/internal/restclient/URLBuilder.java
src/main/java/com/openshift/internal/restclient/capability/CapabilityInitializer.java
src/main/java/com/openshift/internal/restclient/capability/resources/PodLogRetrievalAsync.java
src/main/java/com/openshift/internal/restclient/okhttp/WatchClient.java
src/main/java/com/openshift/internal/restclient/okhttp/WebSocketAdapter.java
src/main/java/com/openshift/restclient/IApiTypeMapper.java
src/main/java/com/openshift/restclient/capability/IStoppable.java
src/main/java/com/openshift/restclient/capability/resources/IPodLogRetrievalAsync.java
src/main/java/com/openshift/restclient/http/IHttpConstants.java
src/test/java/com/openshift/internal/restclient/URLBuilderTest.java
src/test/java/com/openshift/internal/restclient/capability/resources/IPodLogRetrievalAsyncOptionsTest.java
src/test/java/com/openshift/internal/restclient/capability/resources/PodLogRetrievalAsyncIntegrationTest.java
src/test/java/com/openshift/internal/restclient/capability/resources/PodLogRetrievalAsyncTest.java

This PR add a new capability
* retrieve logs without binary dependency

[OSJC-262] Retrieve logs via websocket

---

src/main/java/com/openshift/internal/restclient/model/KubernetesEvent.java
src/main/java/com/openshift/restclient/model/IEvent.java
src/test/java/com/openshift/internal/restclient/model/v1/EventTest.java
src/test/java/com/openshift/restclient/utils/Samples.java
src/test/resources/samples/openshift3/v1_event.json

[OSJC-267] Add property accessors for events

---

src/main/java/com/openshift/restclient/ClientBuilder.java

[JBIDE-22861] - Extend API to allow control of max web socket call limits

---

src/main/java/com/openshift/internal/restclient/capability/resources/BuildTrigger.java
src/main/java/com/openshift/internal/restclient/model/build/BuildRequest.java
src/main/java/com/openshift/restclient/capability/resources/IBuildTriggerable.java
src/main/java/com/openshift/restclient/model/build/IBuildRequest.java
src/test/java/com/openshift/internal/restclient/capability/resources/BuildCapabilitiesIntegrationTest.java

this is the addition (aside from the build log stuff) that we chatted about recently

add cause to build request

---

src/main/java/com/openshift/internal/restclient/DefaultClient.java

cc @bdshadow   Updated per your comment https://github.com/jbosstools/jbosstools-openshift/pull/1277#issuecomment-238545407

Update hash/equals to use baseUrl.toString in follow-up to [jbide-22471]

---

pom.xml

bump pom for 5.0.0-RC1

---

pom.xml

bump pom.xml to 5.1.0-SNAPSHOT

---

src/main/java/com/openshift/internal/restclient/model/Route.java
src/main/java/com/openshift/restclient/model/route/IRoute.java
src/main/java/com/openshift/restclient/model/route/ITargetPort.java
src/test/java/com/openshift/internal/restclient/model/v1/RouteTest.java
src/test/java/com/openshift/restclient/utils/Samples.java
src/test/resources/samples/openshift3/v1_route_port_name.json
src/test/resources/samples/openshift3/v1_route_port_numeric.json

[JBIDE-23015] - Creating a route should have a default port

---

README.md

Add a space so the numbered list is rendered correctly.
@jcantrill

fix testing section of README for numbered list

---

src/main/java/com/openshift/internal/restclient/model/List.java

@jeffmaury @adietish  fix to list that was talked about earlier.  I'm not sure why 'object' was ever in there as I can not find reference to it in the origin code base.

fix list returning objects.  It's not a thing

---

src/main/java/com/openshift/internal/restclient/model/Container.java
src/main/java/com/openshift/internal/restclient/model/Service.java
src/main/java/com/openshift/internal/util/JBossDmrExtentions.java
src/main/java/com/openshift/restclient/model/IContainer.java
src/main/java/com/openshift/restclient/model/IService.java
src/test/java/com/openshift/internal/restclient/model/v1/PodTest.java
src/test/java/com/openshift/internal/restclient/model/v1/ServiceTest.java
src/test/java/com/openshift/internal/util/JBossDmrExtentionsTest.java
src/test/resources/samples/openshift3/v1_pod.json

Add "command" and "args" attribute to IContainer, and add ability to supply port name to the IService.addPort method.

Fixes for container command args and service port names

---

src/main/java/com/openshift/restclient/ClientBuilder.java

(cherry picked from commit b9ab0d5)

setter for proxyAuthenticator okhttp

---

src/main/java/com/openshift/internal/restclient/model/Service.java
src/main/java/com/openshift/restclient/model/IService.java
src/test/java/com/openshift/internal/restclient/model/v1/ServiceTest.java

Added getter and setter for [Service type](http://kubernetes.io/docs/user-guide/services/#publishing-services---service-types)

Added setter and getter for Service type

---

src/main/java/com/openshift/internal/restclient/ResourceFactory.java
src/test/java/com/openshift/internal/restclient/model/v1/ConfigMapTest.java

add configmap back in

---

pom.xml
src/main/java/com/openshift/internal/restclient/model/BuildConfig.java
src/test/java/com/openshift/internal/restclient/model/BuildConfigTest.java

[OSJC-274] - When creating an app from a builder image template, expanding the buildconfig causes

---

src/main/java/com/openshift/internal/restclient/ResourceFactory.java
src/main/java/com/openshift/internal/restclient/api/models/Endpoints.java
src/main/java/com/openshift/restclient/ResourceKind.java
src/main/java/com/openshift/restclient/api/models/IEndpoints.java
src/test/java/com/openshift/internal/restclient/model/v1/EndpointsTest.java
src/test/java/com/openshift/restclient/utils/Samples.java
src/test/resources/samples/openshift3/api/v1_endpoints.json

fixes #242 by adding Endpoints
[test]

[OSJC-242] Add Endpoints

---

src/main/java/com/openshift/internal/restclient/DefaultClient.java
src/main/java/com/openshift/internal/restclient/api/capabilities/ScaleCapability.java
src/main/java/com/openshift/internal/restclient/capability/resources/DeploymentTrigger.java
src/main/java/com/openshift/internal/restclient/model/build/BuildConfigBuilder.java
src/main/java/com/openshift/restclient/IClient.java
src/main/java/com/openshift/restclient/model/IResourceBuilder.java
src/test/java/com/openshift/internal/restclient/DefaultClientFilterIntegrationTest.java
src/test/java/com/openshift/internal/restclient/DefaultClientTest.java

client side filtering of get requests

---

README.md
src/test/java/com/openshift/internal/restclient/authorization/AuthorizationKindsIntegrationTest.java

[test]  cc @adietish @jeffmaury 
Adding to verify #241

[OSJC-241] Add int test for authorization kinds

---

src/main/java/com/openshift/internal/restclient/DefaultClient.java
src/main/java/com/openshift/internal/restclient/URLBuilder.java
src/main/java/com/openshift/restclient/IClient.java
src/test/java/com/openshift/internal/restclient/URLBuilderTest.java

Orc 248 namespaced urls

---

pom.xml
src/main/java/com/openshift/internal/restclient/URLBuilder.java
src/test/java/com/openshift/internal/restclient/DefaultClientIntegrationTest.java
src/test/java/com/openshift/internal/restclient/URLBuilderTest.java

(cherry picked from commit 4de8c19ef626cc59cc085b551ad36fd3852a740a)

[JBIDE-23865] Treat projects differently when building URL

---

src/main/java/com/openshift/internal/restclient/ApiTypeMapper.java

This fixes #264 by making `ApiTypeMapper#init` `synchronized`. (Later, if it becomes important, the lock-free initialization can be revisited.)

Thread safely initialize ApiTypeMapper (#264)

---

src/main/java/com/openshift/restclient/ClientBuilder.java

support multiple certs for SSL connection

---

src/main/java/com/openshift/restclient/ClientBuilder.java

@jcantrill - during some debug with the struggles on us-east prod online offering, some of the analysis pointed to the "okhttp" client creating an abundance of watches.  By default okhttp uses its Version class to set the User-Agent.
Of course, there are multiple users of okhttp under the openshift/eclispe/fabric umbrella :-)
I've started updating some of the relevant repos (at least the ones our Jenkins image brings in) to get a little more specific wrt setting the User-Agent, following an approach that fabric employs.
ptal
@bparees fyi

add restclient prefix to normal okhttp setting of user-agent

---

pom.xml
src/test/java/com/openshift/internal/restclient/TypeMapperFixture.java
src/test/java/com/openshift/internal/restclient/okhttp/WatchClientTest.java

see https://github.com/openshift/jenkins-plugin/issues/147
both unit tests and integration tests looked good
@jcantrill fyi

bump okhttp

---

src/main/java/com/openshift/internal/restclient/model/Container.java
src/main/java/com/openshift/restclient/model/IContainer.java
src/test/java/com/openshift/internal/restclient/model/v1/PodTest.java
src/test/resources/samples/openshift3/v1_pod.json

[OSJC-281] - Provide support for CPU and memory settings

---

src/main/java/com/openshift/internal/restclient/capability/resources/AssociationCapability.java
src/main/java/com/openshift/internal/restclient/capability/resources/DeployCapability.java
src/main/java/com/openshift/internal/restclient/capability/resources/ImageStreamImportCapability.java
src/main/java/com/openshift/internal/restclient/model/ConfigMap.java
src/main/java/com/openshift/internal/restclient/model/Lifecycle.java
src/main/java/com/openshift/internal/restclient/model/Pod.java
src/main/java/com/openshift/internal/restclient/model/ReplicationController.java
src/main/java/com/openshift/internal/restclient/model/volume/PersistentVolumeClaimVolumeSource.java
src/test/java/com/openshift/internal/restclient/APIModelVersionTest.java
src/test/java/com/openshift/internal/restclient/DefaultClientTest.java
src/test/java/com/openshift/internal/restclient/capability/resources/ImageStreamImportCapabilityTest.java
src/test/java/com/openshift/internal/restclient/model/build/BuildRequestTest.java
src/test/java/com/openshift/internal/restclient/model/v1/EmptyDirVolumeSourceTest.java
src/test/java/com/openshift/internal/restclient/model/v1/ImageStreamTest.java
src/test/java/com/openshift/internal/restclient/model/v1/PodTest.java

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

Remove unused import

---

src/main/java/com/openshift/internal/restclient/DefaultClient.java
src/test/java/com/openshift/internal/restclient/model/v1/EnvironmentVariableTest.java

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

Remove unnecessary @SuppressWarning

---

src/main/java/com/openshift/internal/restclient/model/Container.java
src/main/java/com/openshift/internal/restclient/model/ReplicationController.java
src/main/java/com/openshift/internal/restclient/model/probe/Probe.java
src/main/java/com/openshift/restclient/model/IContainer.java
src/main/java/com/openshift/restclient/model/IReplicationController.java
src/main/java/com/openshift/restclient/model/probe/IProbe.java
src/test/java/com/openshift/internal/restclient/model/v1/PodTest.java
src/test/resources/samples/openshift3/v1_pod.json

impl'd rudimentary support for readiness- and lifeness-probes

---

pom.xml
src/main/java/com/openshift/internal/restclient/capability/resources/AbstractOpenShiftBinaryCapability.java
src/main/java/com/openshift/internal/util/StringSplitter.java
src/main/java/com/openshift/restclient/capability/resources/IRSyncable.java
src/test/java/com/openshift/internal/restclient/api/capabilities/PodExecIntegrationTest.java
src/test/java/com/openshift/internal/restclient/capability/resources/OpenshiftBinaryRSyncRetrievalIntegrationTest.java
src/test/java/com/openshift/internal/util/StringSplitterTest.java

#300 Rsync is not working when the local folder path contains a space

---

.travis.yml
pom.xml

[OSJC-282] - Check Java9 compatibility

---

src/main/java/com/openshift/internal/restclient/capability/resources/AbstractOpenShiftBinaryCapability.java
src/main/java/com/openshift/internal/restclient/capability/resources/OpenShiftBinaryRSync.java

[315] fixing git exclusion filter for OSBinaryRSync

---

src/main/java/com/openshift/internal/restclient/model/user/OpenShiftUser.java
src/main/java/com/openshift/restclient/model/user/IUser.java
src/test/java/com/openshift/internal/restclient/model/v1/UserTest.java

[#286] implemented IUser#getUID

---

pom.xml

bumping to 5.9.6.Final

---

src/test/java/com/openshift/internal/restclient/api/capabilities/PodExecIntegrationTest.java

Fix failing integration tests on OCP3.9+

---

src/main/java/com/openshift/internal/restclient/model/properties/ResourcePropertyKeys.java
src/main/java/com/openshift/internal/restclient/model/user/OpenShiftGroup.java
src/main/java/com/openshift/internal/restclient/model/user/OpenShiftIdentity.java
src/main/java/com/openshift/internal/restclient/model/user/OpenShiftUser.java
src/main/java/com/openshift/restclient/ResourceKind.java
src/main/java/com/openshift/restclient/model/user/IGroup.java
src/main/java/com/openshift/restclient/model/user/IIdentity.java
src/test/java/com/openshift/internal/restclient/model/v1/GroupTest.java
src/test/java/com/openshift/internal/restclient/model/v1/IdentityTest.java
src/test/java/com/openshift/internal/restclient/model/v1/UserTest.java
src/test/java/com/openshift/restclient/utils/Samples.java
src/test/resources/samples/openshift3/v1_group.json
src/test/resources/samples/openshift3/v1_identity.json
src/test/resources/samples/openshift3/v1_user.json

This PR should resolve #344. Since I could not get a hold on the UserIdentityMapping I did not implement that endpoint.
I also added the reference list to the already existing users endpoint.

This PR implements the groups and identities endpoints

---

src/main/java/com/openshift/internal/restclient/model/ServicePort.java
src/main/java/com/openshift/restclient/model/IServicePort.java
src/test/java/com/openshift/internal/restclient/model/PortFactory.java
src/test/java/com/openshift/internal/restclient/model/v1/ServiceTest.java
src/test/resources/samples/openshift3/v1_service.json

added setter and getter for nodePort
tests changed
fixes #235

nodePort enhancement

---

pom.xml

bump to 7.0.0.Final

---

src/main/java/com/openshift/internal/restclient/ApiTypeMapper.java
src/main/java/com/openshift/internal/restclient/DefaultClient.java
src/main/java/com/openshift/internal/restclient/model/ModelNodeAdapter.java
src/test/java/com/openshift/internal/restclient/DefaultClientTest.java

Make sure http delete is using payload

---

src/main/java/com/openshift/internal/restclient/DefaultClient.java
src/test/java/com/openshift/internal/restclient/DefaultClientTest.java
src/test/java/com/openshift/internal/restclient/TypeMapperFixture.java

[363] dont send resource in payload when DefaultClient#delete(IResource)

---

pom.xml

bump to 7.1.0.Final

---

src/main/java/com/openshift/internal/restclient/DefaultClient.java
src/test/java/com/openshift/internal/restclient/DefaultClientConstructionTest.java
src/test/java/com/openshift/internal/restclient/TypeMapperFixture.java

[373] silence errors when determining master version

---

src/main/java/com/openshift/internal/restclient/model/Pod.java
src/main/java/com/openshift/restclient/model/IPod.java
src/test/java/com/openshift/internal/restclient/model/v1/PodTest.java
src/test/java/com/openshift/restclient/utils/Samples.java
src/test/resources/samples/openshift3/v1_pod_multiContainer_ready.json

 [360] impl'd IPod#isReady that relies on all containers to be ready

---

pom.xml

releasing 7.1.1.Final

---

pom.xml

Bumping to 8.0.0-SNAPSHOT as we are going to support OpenShift 4

---

pom.xml
src/main/java/com/openshift/internal/restclient/DefaultClient.java
src/main/java/com/openshift/internal/restclient/KubernetesVersion.java
src/main/java/com/openshift/internal/restclient/OpenShiftMajorVersion.java
src/main/java/com/openshift/internal/restclient/capability/CapabilityInitializer.java
src/main/java/com/openshift/internal/restclient/capability/server/Console.java
src/main/java/com/openshift/internal/restclient/model/volume/PersistentVolumeClaim.java
src/main/java/com/openshift/restclient/IClient.java
src/main/java/com/openshift/restclient/capability/server/IConsole.java
src/test/java/com/openshift/internal/restclient/DefaultClientIntegrationTest.java
src/test/java/com/openshift/internal/restclient/IntegrationTestHelper.java
src/test/java/com/openshift/internal/restclient/KubernetesVersionTest.java
src/test/java/com/openshift/internal/restclient/OpenShiftVersionTest.java
src/test/java/com/openshift/internal/restclient/capability/server/ConsoleIntegrationTest.java
src/test/java/com/openshift/internal/restclient/capability/server/DataPair.java
src/test/java/com/openshift/internal/restclient/capability/server/OpenShift3ConsoleTest.java
src/test/java/com/openshift/internal/restclient/capability/server/OpenShift4ConsoleTest.java
src/test/java/com/openshift/restclient/utils/Samples.java
src/test/resources/samples/openshift3/v1_config_map_console_public.json

impl'd capability to retrieve console url (#400)

---

.travis.yml
startOCP.sh

Test running ITs on Travis

---

.travis.yml

fixes #405 
switching to openjdk like others do: https://github.com/authorjapps/zerocode/pull/324

fixing travis build by switching to openjdk

---

src/main/java/com/openshift/internal/restclient/DefaultClient.java
src/main/java/com/openshift/internal/restclient/okhttp/AuthenticatorInterceptor.java

fixes https://issues.jboss.org/browse/JBIDE-26915

/healthz should not trigger auth

---

pom.xml

upgrade log4j, sl4j to latest versions (#418)

---

.travis.yml
startOCP.sh

Fix OCP startup script

---

src/test/resources/log4j.xml

Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

Issue-418 Update log4j configuration for 2.13.0

---

pom.xml

depends on #432 which has to be merged first

Bump sl4j api version

---

src/main/java/com/openshift/internal/restclient/DefaultClient.java
src/test/java/com/openshift/internal/restclient/AuthorizationEndpointsTest.java

use default auth endpoint if discovering fails

---

src/main/java/com/openshift/internal/restclient/model/EnvironmentVariable.java
src/main/java/com/openshift/restclient/model/IObjectFieldSelector.java
src/test/java/com/openshift/internal/restclient/model/v1/ReplicationControllerTest.java
src/test/resources/samples/openshift3/v1_replication_controller.json

fixed erroneous prop retrieval in EnvVar.getValueFrom() (#444)

---

src/main/java/com/openshift/internal/restclient/AuthorizationEndpoints.java
src/main/java/com/openshift/internal/restclient/RequestingSupplier.java

lowered logging level for non harmful request failures (#450)

---

src/main/java/com/openshift/restclient/http/IHttpConstants.java

update resource support Chinese character (#456)

Fix (#456)

---

src/main/java/com/openshift/internal/restclient/authorization/AuthorizationContext.java
src/main/java/com/openshift/restclient/authorization/IAuthorizationContext.java
src/test/java/com/openshift/internal/restclient/authorization/AuthorizationContextTest.java

impl'd AuthorizationContext#invalidate (#455)

---

src/main/java/com/openshift/internal/restclient/ApiTypeMapper.java

corrected logging for inaccessible legacy apis to info (#462)

---

pom.xml
src/main/java/com/openshift/restclient/model/kubeclient/KubeClientConfigSerializer.java

- commons-compress bumped to 1.21
- snakeyaml bumped to 1.19

OSJC-288: Fix CVEs from commons-compress and snakeyaml

---

pom.xml
src/main/java/com/openshift/internal/restclient/DefaultClient.java
src/main/java/com/openshift/internal/restclient/capability/resources/AbstractOpenShiftBinaryCapability.java
src/main/java/com/openshift/internal/restclient/capability/resources/OpenShiftBinaryRSync.java
src/main/java/com/openshift/internal/restclient/model/kubeclient/KubeClientConfigConstructor.java
src/main/java/com/openshift/restclient/ClientBuilder.java
src/test/java/com/openshift/internal/restclient/ResourceFactoryTest.java
src/test/java/com/openshift/internal/restclient/capability/resources/DeployCapabilityTest.java
src/test/java/com/openshift/internal/restclient/capability/resources/ImageStreamImportCapabilityIntegrationTest.java
src/test/java/com/openshift/internal/restclient/capability/resources/OpenShiftBinaryPortForwardingIntegrationTest2.java
src/test/java/com/openshift/internal/restclient/model/ServiceTest.java
src/test/java/com/openshift/internal/restclient/model/v1/EmptyDirVolumeSourceTest.java
src/test/java/com/openshift/internal/restclient/model/v1/HostPathVolumeSourceTest.java
src/test/java/com/openshift/internal/restclient/model/v1/PVCVolumeSourceTest.java
src/test/java/com/openshift/internal/restclient/model/v1/RouteTest.java
src/test/java/com/openshift/internal/restclient/model/v1/SecretVolumeSourceTest.java
src/test/java/com/openshift/internal/restclient/okhttp/WatchClientTest.java
src/test/java/com/openshift/internal/util/JBossDmrExtentionsTest.java
src/test/java/com/openshift/internal/util/StringSplitterTest.java
src/test/java/com/openshift/restclient/OpenShiftContextTest.java
src/test/java/com/openshift/restclient/utils/Samples.java
src/test/resources/samples/openshift3/v1_build_config.json
src/test/resources/samples/openshift3/v1_config_map_list_empty.json
src/test/resources/samples/openshift3/v1_objectref.json
src/test/resources/samples/openshift3/v1_project_request.json
src/test/resources/samples/openshift3/v1_replication_controller.json
src/test/resources/samples/openshift3/v1_route_wo_tls.json

Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>

update dependencies to latest and refactored tests

---

pom.xml

follows up on https://github.com/openshift/openshift-restclient-java/pull/474

release 9.0.4.Final

---

pom.xml

bumped okhttp, snakeyaml, log4j, slf4j, assertj (#476)
